version: '2.1'

services:
  unifiedpushserver:
    image: aerogear/ups:kc
    environment:
        KEYCLOAK_SERVICE_HOST: "localhost"
        KEYCLOAK_SERVICE_PORT: "20001"
    ports:
      - 18080:8080
  keycloakServer:
    image: docker.io/jboss/keycloak:3.4.3.Final
    command: "-b 0.0.0.0 -Dkeycloak.import=/ups-keycloak-config/ups-realm-sample.json"
    volumes:
      - ./keycloak-realm:/ups-keycloak-config:z
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    ports:
      - 20001:8080
