keycloakServer:
  image: jboss/keycloak:3.2.1.Final
  command: "-b 0.0.0.0 -Dkeycloak.import=/ups-keycloak-config/ups-realm-sample.json"
  volumes:
   - ../keycloak-realm:/ups-keycloak-config
  environment:
   - KEYCLOAK_USER=admin
   - KEYCLOAK_PASSWORD=admin
unifiedpushDB:
  image: mysql:5.5
  environment:
    - MYSQL_USER=unifiedpush
    - MYSQL_PASSWORD=unifiedpush
    - MYSQL_DATABASE=unifiedpush
    - MYSQL_ROOT_PASSWORD=supersecret
  ports:
    - 6306:3306
unifiedpushServer:
  image: aerogear/unifiedpush-wildfly:latest
  links:
    - unifiedpushDB:unifiedpush
    - keycloakServer:keycloak
  depends_on:
    - "unifiedpushDB"
  ports:
    - 10080:8080